services:
  - type: web
    name: epicclub-backend
    runtime: node
    rootDir: epicclub-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://postgres.qkxxmwgdpgwakxnfyabj:SaidNaidji2006@aws-1-eu-central-1.pooler.supabase.com:6543/postgres
      - key: REDIS_URL
        value: rediss://default:AaSDAAIgcDE0ODFkM2I0MTU0ZGM0ODE3YjIxNzliM2M1NGM2MmIwZA@topical-kiwi-42115.upstash.io:6379
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 599980788199-log1ipgcl3pm0mh7eleab9em26i423cf.apps.googleusercontent.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://epicclub-frontend.vercel.app,https://epicclub-frontend-4otl7nq07-epic-office.vercel.app,http://localhost:3000
      - key: FRONTEND_URL
        value: https://epicclub-frontend.vercel.app
